<a href="https://colab.research.google.com/github/davidclizbe/datascience/blob/master/ClizbeBuildingandAnalyzingPerformance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_digits
X,y = load_digits(return_X_y= True)

In [ ]:
X

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [ ]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [ ]:
import numpy as np
num_rows = np.shape(X)[0]
num_columns = np.shape(X)[1]
print('The number of rows in the dataset is {:d}'.format(num_rows))
print('The number of features in the dataset is {:d}'.format(num_columns))
np.bincount(y)

The number of rows in the dataset is 1797
The number of features in the dataset is 64


array([178, 182, 177, 183, 181, 182, 181, 179, 174, 180])

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.2, random_state = 300)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

lr_clf = LogisticRegression(C = 1.0, solver= 'lbfgs', multi_class ='ovr', max_iter=1000)
lr_cv_scores = cross_val_score(lr_clf, X_train, y_train, cv = 10)

print('Accuracy scores for the 10 folds: ', lr_cv_scores)
print('Mean cross validation score: {:.3f}'.format(np.mean(lr_cv_scores)))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Accuracy scores for the 10 folds:  [0.94444444 0.97916667 0.92361111 0.97222222 0.95833333 0.95833333
 0.97222222 0.96503497 0.93706294 0.96503497]
Mean cross validation score: 0.958


In [ ]:
# imports here
from sklearn.ensemble import RandomForestClassifier


rf_clf = RandomForestClassifier(n_estimators=24)
rf_cv_scores = cross_val_score(rf_clf, X_train, y_train, cv =10)

print('Accuracy scores for the 5 folds: ', rf_cv_scores)
print('Mean cross validation score: {:.3f}'.format(np.mean(rf_cv_scores)))

Accuracy scores for the 5 folds:  [0.97222222 0.96527778 0.94444444 0.98611111 0.95138889 0.95138889
 0.95833333 0.97902098 0.96503497 0.99300699]
Mean cross validation score: 0.967
